name: 'Android Appium Workflow Action'
description: 'Custom GitHub Action to run Appium tests with Maven.'
inputs:
  java_version:
    description: 'The version of Java to install.'
    required: false
    default: '22'

  api_level:
    description: 'The SDK level'
    required: false
    default: '35'

  node_version:
    description: 'The version of NodeJS to install.'
    required: false
    default: '21'

  test_name:
    description: 'The name of the test suite.'
    required: true

  scripts:
    description: 'The maven commands to execute the test.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}

    - name: Install FFmpeg
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update > /dev/null 2>&1
        sudo apt-get install -y ffmpeg > /dev/null 2>&1
      shell: bash

    - name: Install FFmpeg
      if: runner.os == 'macOS'
      run: brew install ffmpeg > /dev/null 2>&1
      shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: Create and start emulator
      uses: ThangNguyen0495/create-android-emulator@main
      with:
        api-level: ${{ inputs.api_level }}

    - name: Install Appium
      run: npm install -g appium > /dev/null 2>&1
      shell: bash

    - name: Install UIAutomator2 driver
      run: appium driver install uiautomator2 > /dev/null 2>&1
      shell: bash

    - name: Start Appium server
      run: |
        nohup appium -a 0.0.0.0 -p 4723 -pa /wd/hub > appium_log.txt 2>&1 & > /dev/null 2>&1
      shell: bash

    - name: Install dependencies
      run: |
        mvn install -DskipTests > /dev/null 2>&1
      shell: bash

    - name: Run Appium tests and capture logs
      run: |
        eval "${{ inputs.scripts }}
      shell: bash
      continue-on-error: true  # Allows the next step to run even if this one fails
      
    - name: Check logs and restart emulator if needed
      run: |
        if grep -q "SessionNotCreated Could not start a new session." appium_log.txt; then
          echo "⚠️ Detected 'SessionNotCreated' error, restarting ADB and Emulator..."
    
          echo "Force stopping the emulator..."
          adb emu kill
          sleep 5
    
          echo "Starting emulator again..."
          nohup $HOME/android-sdk/emulator/emulator -avd emu -no-metrics -no-snapshot-load -no-snapshot-save -no-boot-anim -wipe-data -no-window -gpu swiftshader_indirect -delay-adb > emulator.log 2>&1 &
          disown
    
          echo "Waiting for emulator to come online..."
          $ANDROID_HOME/platform-tools/adb wait-for-device
    
          echo "Checking if the emulator is fully booted..."
          boot_completed=""
          while [ "$boot_completed" != "1" ]; do
            sleep 5
            boot_completed=$($ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed 2>/dev/null)
            echo "Still waiting for emulator to boot fully..."
          done
    
          echo "Emulator is fully booted!"
          $ANDROID_HOME/platform-tools/adb devices
    
          echo "Retrying test..."
          eval "${{ inputs.scripts }}" || { echo "❌ Test failed even after retry!"; exit 1; }
        else
          echo "✅ No 'SessionNotCreated' error found, skipping emulator restart."
          exit 1
        fi
      shell: bash
  
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Reports - ${{ inputs.test_name }}
        path: |
          **/target/BufferLog.log
          **/target/ExtentReport.html
